### ISSUE TITLE
Feature suggestion: Support the dev.azure.com domain/URL

### ISSUE THREAD

**Issue by OranguTech** [emragins/chrome-azure-devops#1]
See https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sep-10-azure-devops-launch#administration

**Comment by emragins** [comment]
Absolutely -- I had no idea this even existed.  It looks like this is probably something where people should have the option for which domain they're using, at least for as long as microsoft is giving people that option.

**Comment by OranguTech** [comment]
@emragins - that branch worked for me! (Thanks for the readme explaining how to use dev/unpacked mode as well)

It didn't auto-load my previous settings, I assume due to how chrome extension versioning/storage works.

**Comment by emragins** [comment]
This should actually be resolved now, as the code is merged into master.
